import moment from 'moment';

// function getDay(day = 0) {
//     return moment().add(day, 'days').format('YYYY.MM.DD');
// }
function getTime(day = 0, second = 0) {
    return moment()
        .add(day, 'days')
        .add(second, 'seconds')
        .format('YYYY.MM.DD HH:mm:ss');
}

export const initData = async (clientId, nextSeq) => {
    return {
        // 회원
        user: [
            {
                _id: await nextSeq('user'),
                email: 'admin@market.com',
                password:
                    '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
                name: '무지',
                type: 'admin',
                image: `/files/${clientId}/user-muzi.webp`,
                createdAt: getTime(-100, -60 * 60 * 3),
                updatedAt: getTime(-100, -60 * 60 * 3),
            },
            {
                _id: await nextSeq('user'),
                email: 's1@market.com',
                password:
                    '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
                name: '네오',
                type: 'seller',
                image: `/files/${clientId}/user-neo.webp`,
                createdAt: getTime(-50),
                updatedAt: getTime(-30, -60 * 60 * 3),
            },
            {
                _id: await nextSeq('user'),
                email: 'u1@market.com',
                password:
                    '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
                name: '어피치',
                type: 'user',
                createdAt: getTime(-40, -60 * 30),
                updatedAt: getTime(-30, -60 * 20),
            },
            {
                _id: await nextSeq('user'),
                email: 'test@test.com',
                password:
                    '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
                name: '테스트계정 형식',
                type: 'user',
                phone: '01012345678',
                zoneCode: '12345',
                roadAddress: '경기도 어딘가',
                detailAddress: '1',
                loginType: 'email',
                createdAt: getTime(),
                updatedAt: getTime(),
                extra: {
                    baby: {
                        name: '베이비',
                        gender: 'boy',
                        birth: '20240801',
                        grow: [
                            {
                                weight: '12.3',
                                height: '50',
                                date: '20240802',
                            },
                        ],
                    },
                    subscribe: {
                        status: 'true',
                        date: '20240815',
                    },
                },
            },
        ],
        // 상품
        // 현재 seller = seller_id : 2 로 설정
        product: [
            {
                _id: await nextSeq('product'),
                name: '기저귀',
                mainImages: [
                    {
                        path: `/files/${clientId}/step1_diaper.webp`,
                        name: 'diaper.webp',
                        originalname: 'diaper.webp',
                    },
                ],
                category: ['ST01'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '젖병',
                mainImages: [
                    {
                        path: `/files/${clientId}/step1_feedingbottle.webp`,
                        name: 'feedingbottle.webp',
                        originalname: 'feedingbottle.webp',
                    },
                ],
                category: ['ST01'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '분유',
                mainImages: [
                    {
                        path: `/files/${clientId}/step1_powderedmilk.webp`,
                        name: 'powderedmilk.webp',
                        originalname: 'powderedmilk.webp',
                    },
                ],
                category: ['ST01'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '체온계',
                mainImages: [
                    {
                        path: `/files/${clientId}/step1_thermometer.webp`,
                        name: 'thermometer.webp',
                        originalname: 'thermometer.webp',
                    },
                ],
                category: ['ST01'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '아기 손수건',
                mainImages: [
                    {
                        path: `/files/${clientId}/step1_handkerchief.webp`,
                        name: 'handkerchief.webp',
                        originalname: 'handkerchief.webp',
                    },
                ],
                category: ['ST01'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '모빌',
                mainImages: [
                    {
                        path: `/files/${clientId}/step1_mobile.webp`,
                        name: 'mobile.webp',
                        originalname: 'mobile.webp',
                    },
                ],
                category: ['ST01'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '아기띠',
                mainImages: [
                    {
                        path: `/files/${clientId}/step1_babycarrier.webp`,
                        name: 'babycarrier.webp',
                        originalname: 'babycarrier.webp',
                    },
                ],
                category: ['ST01'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '턱받이',
                mainImages: [
                    {
                        path: `/files/${clientId}/step1_bib.webp`,
                        name: 'bib.webp',
                        originalname: 'bib.webp',
                    },
                ],
                category: ['ST01'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '쪽쪽이',
                mainImages: [
                    {
                        path: `/files/${clientId}/step1_pacifier.webp`,
                        name: 'pacifier.webp',
                        originalname: 'pacifier.webp',
                    },
                ],
                category: ['ST01'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '손싸개',
                mainImages: [
                    {
                        path: `/files/${clientId}/step1_handwarmer.webp`,
                        name: 'handwarmer.webp',
                        originalname: 'handwarmer.webp',
                    },
                ],
                category: ['ST01'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '이유식기',
                mainImages: [
                    {
                        path: `/files/${clientId}/step2_babyfoodtools.webp`,
                        name: 'babyfoodtools.webp',
                        originalname: 'babyfoodtools.webp',
                    },
                ],
                category: ['ST02'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '놀이매트',
                mainImages: [
                    {
                        path: `/files/${clientId}/step2_playmat.webp`,
                        name: 'playmat.webp',
                        originalname: 'playmat.webp',
                    },
                ],
                category: ['ST02'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '식사 보조기',
                mainImages: [
                    {
                        path: `/files/${clientId}/step2_mealaid.webp`,
                        name: 'mealaid.webp',
                        originalname: 'mealaid.webp',
                    },
                ],
                category: ['ST02'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '치발기',
                mainImages: [
                    {
                        path: `/files/${clientId}/step2_teether.webp`,
                        name: 'teether.webp',
                        originalname: 'teether.webp',
                    },
                ],
                category: ['ST02'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '젖병 세척 용품',
                mainImages: [
                    {
                        path: `/files/${clientId}/step2_bottlewasher.webp`,
                        name: 'bottlewasher.webp',
                        originalname: 'bottlewasher.webp',
                    },
                ],
                category: ['ST02'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '자외선 차단제',
                mainImages: [
                    {
                        path: `/files/${clientId}/step2_sunscreen.webp`,
                        name: 'sunscreen.webp',
                        originalname: 'sunscreen.webp',
                    },
                ],
                category: ['ST02'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '물병',
                mainImages: [
                    {
                        path: `/files/${clientId}/step2_waterbottle.webp`,
                        name: 'waterbottle.webp',
                        originalname: 'waterbottle.webp',
                    },
                ],
                category: ['ST02'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '목욕타올',
                mainImages: [
                    {
                        path: `/files/${clientId}/step2_bathtowel.webp`,
                        name: 'bathtowel.webp',
                        originalname: 'bathtowel.webp',
                    },
                ],
                category: ['ST02'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '목욕용품',
                mainImages: [
                    {
                        path: `/files/${clientId}/step2_bathsupplies.webp`,
                        name: 'bathsupplies.webp',
                        originalname: 'bathsupplies.webp',
                    },
                ],
                category: ['ST02'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '애기 로션',
                mainImages: [
                    {
                        path: `/files/${clientId}/step2_babylotion.webp`,
                        name: 'babylotion.webp',
                        originalname: 'babylotion.webp',
                    },
                ],
                category: ['ST02'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '장난감',
                mainImages: [
                    {
                        path: `/files/${clientId}/step3_toys.webp`,
                        name: 'toys.webp',
                        originalname: 'toys.webp',
                    },
                ],
                category: ['ST03'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '체중계',
                mainImages: [
                    {
                        path: `/files/${clientId}/step3_scale.webp`,
                        name: 'scale.webp',
                        originalname: 'scale.webp',
                    },
                ],
                category: ['ST03'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '기저귀',
                mainImages: [
                    {
                        path: `/files/${clientId}/step3_diapers.webp`,
                        name: 'diapers.webp',
                        originalname: 'diapers.webp',
                    },
                ],
                category: ['ST03'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '빨대컵',
                mainImages: [
                    {
                        path: `/files/${clientId}/step3_strawcup.webp`,
                        name: 'strawcup.webp',
                        originalname: 'strawcup.webp',
                    },
                ],
                category: ['ST03'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '아기용 수건',
                mainImages: [
                    {
                        path: `/files/${clientId}/step3_babytowel.webp`,
                        name: 'babytowel.webp',
                        originalname: 'babytowel.webp',
                    },
                ],
                category: ['ST03'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '소리나는 책',
                mainImages: [
                    {
                        path: `/files/${clientId}/step3_soundbook.webp`,
                        name: 'soundbook.webp',
                        originalname: 'soundbook.webp',
                    },
                ],
                category: ['ST03'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '과일 쪽쪽이',
                mainImages: [
                    {
                        path: `/files/${clientId}/step3_babyfruit.webp`,
                        name: 'babyfruit.webp',
                        originalname: 'babyfruit.webp',
                    },
                ],
                category: ['ST03'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '아기용 식판',
                mainImages: [
                    {
                        path: `/files/${clientId}/step3_babyplate.webp`,
                        name: 'babyplate.webp',
                        originalname: 'babyplate.webp',
                    },
                ],
                category: ['ST03'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '아기용 손수건',
                mainImages: [
                    {
                        path: `/files/${clientId}/step3_handkerchief.webp`,
                        name: 'handkerchief.webp',
                        originalname: 'handkerchief.webp',
                    },
                ],
                category: ['ST03'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '보드북',
                mainImages: [
                    {
                        path: `/files/${clientId}/step4_boardbook.webp`,
                        name: 'boardbook.webp',
                        originalname: 'boardbook.webp',
                    },
                ],
                category: ['ST04'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '책',
                mainImages: [
                    {
                        path: `/files/${clientId}/step4_book.webp`,
                        name: 'book.webp',
                        originalname: 'book.webp',
                    },
                ],
                category: ['ST04'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '모서리 보호대',
                mainImages: [
                    {
                        path: `/files/${clientId}/step4_cornerprotector.webp`,
                        name: 'cornerprotector.webp',
                        originalname: 'cornerprotector.webp',
                    },
                ],
                category: ['ST04'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '문 안전장치',
                mainImages: [
                    {
                        path: `/files/${clientId}/step4_doorlocker.webp`,
                        name: 'doorlocker.webp',
                        originalname: 'doorlocker.webp',
                    },
                ],
                category: ['ST04'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '구급상자',
                mainImages: [
                    {
                        path: `/files/${clientId}/step4_firstaidkit.webp`,
                        name: 'firstaidkit.webp',
                        originalname: 'firstaidkit.webp',
                    },
                ],
                category: ['ST04'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '모자',
                mainImages: [
                    {
                        path: `/files/${clientId}/step4_hat.webp`,
                        name: 'hat.webp',
                        originalname: 'hat.webp',
                    },
                ],
                category: ['ST04'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '서랍장 잠금장치',
                mainImages: [
                    {
                        path: `/files/${clientId}/step4_locker.webp`,
                        name: 'locker.webp',
                        originalname: 'locker.webp',
                    },
                ],
                category: ['ST04'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '단계별 장난감',
                mainImages: [
                    {
                        path: `/files/${clientId}/step4_steptoys.webp`,
                        name: 'steptoys.webp',
                        originalname: 'steptoys.webp',
                    },
                ],
                category: ['ST04'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '식기 세트',
                mainImages: [
                    {
                        path: `/files/${clientId}/step4_tableware.webp`,
                        name: 'tableware.webp',
                        originalname: 'tableware.webp',
                    },
                ],
                category: ['ST04'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '보행기',
                mainImages: [
                    {
                        path: `/files/${clientId}/step4_walker.webp`,
                        name: 'walker.webp',
                        originalname: 'walker.webp',
                    },
                ],
                category: ['ST04'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '뽁뽁이 신발',
                mainImages: [
                    {
                        path: `/files/${clientId}/step5_soundshoes.webp`,
                        name: 'soundshoes.webp',
                        originalname: 'soundshoes.webp',
                    },
                ],
                category: ['ST05'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '블럭',
                mainImages: [
                    {
                        path: `/files/${clientId}/step5_block.webp`,
                        name: 'block.webp',
                        originalname: 'block.webp',
                    },
                ],
                category: ['ST05'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '퍼즐',
                mainImages: [
                    {
                        path: `/files/${clientId}/step5_puzzle.webp`,
                        name: 'puzzle.webp',
                        originalname: 'puzzle.webp',
                    },
                ],
                category: ['ST05'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '미술용품',
                mainImages: [
                    {
                        path: `/files/${clientId}/step5_artsupplies.webp`,
                        name: 'artsupplies.webp',
                        originalname: 'artsupplies.webp',
                    },
                ],
                category: ['ST05'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '아기 욕조',
                mainImages: [
                    {
                        path: `/files/${clientId}/step5_babybath.webp`,
                        name: 'babybath.webp',
                        originalname: 'babybath.webp',
                    },
                ],
                category: ['ST05'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '아기 세면대',
                mainImages: [
                    {
                        path: `/files/${clientId}/step5_babysink.webp`,
                        name: 'babysink.webp',
                        originalname: 'babysink.webp',
                    },
                ],
                category: ['ST05'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '스케치북',
                mainImages: [
                    {
                        path: `/files/${clientId}/step5_sketchbook.webp`,
                        name: 'sketchbook.webp',
                        originalname: 'sketchbook.webp',
                    },
                ],
                category: ['ST05'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '소리나는 장난감',
                mainImages: [
                    {
                        path: `/files/${clientId}/step5_soundtoys.webp`,
                        name: 'soundtoys.webp',
                        originalname: 'soundtoys.webp',
                    },
                ],
                category: ['ST05'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '그림책',
                mainImages: [
                    {
                        path: `/files/${clientId}/step5_picturebook.webp`,
                        name: 'picturebook.webp',
                        originalname: 'picturebook.webp',
                    },
                ],
                category: ['ST05'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '대근육 발달 놀이기구',
                mainImages: [
                    {
                        path: `/files/${clientId}/step5_muscletoys.webp`,
                        name: 'muscletoys.webp',
                        originalname: 'muscletoys.webp',
                    },
                ],
                category: ['ST05'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '자동차 장난감',
                mainImages: [
                    {
                        path: `/files/${clientId}/step6_cartoys.webp`,
                        name: 'cartoys.webp',
                        originalname: 'cartoys.webp',
                    },
                ],
                category: ['ST06'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '미끄럼틀',
                mainImages: [
                    {
                        path: `/files/${clientId}/step6_slide.webp`,
                        name: 'slide.webp',
                        originalname: 'slide.webp',
                    },
                ],
                category: ['ST06'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '모래놀이 세트',
                mainImages: [
                    {
                        path: `/files/${clientId}/step6_sandplay.webp`,
                        name: 'sandplay.webp',
                        originalname: 'sandplay.webp',
                    },
                ],
                category: ['ST06'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '아기 배낭',
                mainImages: [
                    {
                        path: `/files/${clientId}/step6_babybag.webp`,
                        name: 'babybag.webp',
                        originalname: 'babybag.webp',
                    },
                ],
                category: ['ST06'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '아기 비누',
                mainImages: [
                    {
                        path: `/files/${clientId}/step6_babysoap.webp`,
                        name: 'babysoap.webp',
                        originalname: 'babysoap.webp',
                    },
                ],
                category: ['ST06'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '아기 샴푸',
                mainImages: [
                    {
                        path: `/files/${clientId}/step6_shampoo.webp`,
                        name: 'shampoo.webp',
                        originalname: 'shampoo.webp',
                    },
                ],
                category: ['ST06'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '미끄럼 방지 식탁 매트',
                mainImages: [
                    {
                        path: `/files/${clientId}/step6_tablemat.webp`,
                        name: 'tablemat.webp',
                        originalname: 'tablemat.webp',
                    },
                ],
                category: ['ST06'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '자석 장난감',
                mainImages: [
                    {
                        path: `/files/${clientId}/step6_magnetictoys.webp`,
                        name: 'magnetictoys.webp',
                        originalname: 'magnetictoys.webp',
                    },
                ],
                category: ['ST06'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '자전거',
                mainImages: [
                    {
                        path: `/files/${clientId}/step7_bike.webp`,
                        name: 'bike.webp',
                        originalname: 'bike.webp',
                    },
                ],
                category: ['ST07'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '아기 악기',
                mainImages: [
                    {
                        path: `/files/${clientId}/step7_instrument.webp`,
                        name: 'instrument.webp',
                        originalname: 'instrument.webp',
                    },
                ],
                category: ['ST07'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '크레파스',
                mainImages: [
                    {
                        path: `/files/${clientId}/step7_crayon.webp`,
                        name: 'crayon.webp',
                        originalname: 'crayon.webp',
                    },
                ],
                category: ['ST07'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '색연필',
                mainImages: [
                    {
                        path: `/files/${clientId}/step7_coloredpencil.webp`,
                        name: 'coloredpencil.webp',
                        originalname: 'coloredpencil.webp',
                    },
                ],
                category: ['ST07'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '아기 돗자기',
                mainImages: [
                    {
                        path: `/files/${clientId}/step7_mat.webp`,
                        name: 'mat.webp',
                        originalname: 'mat.webp',
                    },
                ],
                category: ['ST07'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '자전거 헬멧',
                mainImages: [
                    {
                        path: `/files/${clientId}/step7_helmet.webp`,
                        name: 'helmet.webp',
                        originalname: 'helmet.webp',
                    },
                ],
                category: ['ST07'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '훈련용 팬티',
                mainImages: [
                    {
                        path: `/files/${clientId}/step7_underwear.webp`,
                        name: 'underwear.webp',
                        originalname: 'underwear.webp',
                    },
                ],
                category: ['ST07'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '시계 장난감',
                mainImages: [
                    {
                        path: `/files/${clientId}/step7_clock.webp`,
                        name: 'clock.webp',
                        originalname: 'clock.webp',
                    },
                ],
                category: ['ST07'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '침대 가드레일',
                mainImages: [
                    {
                        path: `/files/${clientId}/step7_guardrail.webp`,
                        name: 'guardrail.webp',
                        originalname: 'guardrail.webp',
                    },
                ],
                category: ['ST07'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
            {
                _id: await nextSeq('product'),
                name: '알파벳 장난감',
                mainImages: [
                    {
                        path: `/files/${clientId}/step7_alphabet.webp`,
                        name: 'alphabet.webp',
                        originalname: 'alphabet.webp',
                    },
                ],
                category: ['ST07'],
                content: '<div><p>예시 - 설명랑</p></div>',
                quantity: 1,
                seller_id: 1,
                price: 0,
                quantity: 100,
                show: true,
                active: true,
                seller_id: 2,
            },
        ],
        // 주문
        order: [],
        // 후기
        reply: [],
        // 장바구니
        cart: [],
        // 즐겨찾기/북마크
        bookmark: [],
        // QnA, 공지사항, 게시판
        post: [
            {
                _id: await nextSeq('post'),
                type: 'info',
                title: '정보 게시판 사용안내.',
                views: 5,
                user: {
                    _id: 1,
                    name: '무지',
                    image: `/files/${clientId}/user-muzi.webp`,
                },
                content: '좋은 정보 많이 공유해 주세요.',
                replies: [
                    {
                        _id: 1,
                        user_id: 2,
                        user: {
                            _id: 2,
                            name: '네오',
                            image: `/files/${clientId}/user-neo.webp`,
                        },
                        content: '1등',
                        like: 5,
                        createdAt: getTime(-2, -60 * 60 * 20),
                        updatedAt: getTime(-2, -60 * 60 * 2),
                    },
                    {
                        _id: 2,
                        user_id: 3,
                        user: {
                            _id: 3,
                            name: '어피치',
                        },
                        content: '넵',
                        like: 7,
                        createdAt: getTime(-2, -60 * 60 * 10),
                        updatedAt: getTime(-2, -60 * 60 * 1),
                    },
                ],
                createdAt: getTime(-3, -60 * 60 * 2),
                updatedAt: getTime(-3, -60 * 60 * 2),
            },
            {
                _id: await nextSeq('post'),
                type: 'music',
                title: '일일 DJ, GD 입니다',
                views: 5,
                user: {
                    _id: 2,
                    name: '네오',
                    image: `/files/${clientId}/user-neo.webp`,
                },
                content: '좋은 노래 많이 신청해 주세요.',
                replies: [
                    {
                        _id: 1,
                        user_id: 2,
                        user: {
                            _id: 2,
                            name: '네오',
                            image: `/files/${clientId}/user-neo.webp`,
                        },
                        like: 5,
                        content: '삐딱하게 틀어주세요',
                        videoId: 'RKhsHGfrFmY',
                        extra: {
                            artist: 'GD',
                            title: 'G-DRAGON - 삐딱하게(CROOKED) M/V',
                        },
                        createdAt: getTime(-2, -60 * 60 * 20),
                        updatedAt: getTime(-2, -60 * 60 * 2),
                    },
                    {
                        _id: 2,
                        user_id: 3,
                        user: {
                            _id: 3,
                            name: '어피치',
                        },
                        content: '비가오니까 에픽하이의 우산이 듣고 싶어요.',
                        like: 13,
                        videoId: 'NIPtyAKxlRs',
                        extra: {
                            artist: '에픽하이',
                            title: '에픽하이(Epik high) - 우산 (Feat. 윤하)',
                        },
                        createdAt: getTime(-2, -60 * 60 * 10),
                        updatedAt: getTime(-2, -60 * 60 * 1),
                    },
                ],
                createdAt: getTime(-3, -60 * 60 * 2),
                updatedAt: getTime(-3, -60 * 60 * 2),
            },
        ],
        // 코드
        code: [
            {
                _id: 'step',
                title: '단계',
                codes: [
                    {
                        code: 'ST01',
                        value: '0~4개월',
                        description: [
                            '머리를 가누고 근육이 강화돼요.',
                            '가까운 물체를 인식하고 소리에 반응해요.',
                            '엄마, 아빠의 목소리와 얼굴을 인식해요.',
                            '신생아 반사를 보이며 뇌와 신경계가 발달하는 시기에요.',
                        ],
                    },
                    {
                        code: 'ST02',
                        value: '5~7개월',
                        description: [
                            '손과 입을 사용해 다양한 물체를 탐색하고 경험해요.',
                            '옹알이를 시작하고 다양한 소리를 내요.',
                            '엄마, 아빠와의 정서적 유대감이 깊어져요.',
                            '엎드리기, 앉기, 뒤집기 등 운동 능력이 발달하는 시기에요.',
                        ],
                    },
                    {
                        code: 'ST03',
                        value: '8~10개월',
                        description: [
                            '혼자 일어나 앉기, 기어다니기 등 이동 능력이 향상돼요.',
                            '물체를 집고 조작하는 능력이 발달해요.',
                            '단어같은 소리를 내고, 기본적인 의사소통이 이루어져요.',
                            '엄마, 아빠와 상호작용하며 애착이 강화되는 시기에요.',
                        ],
                    },
                    {
                        code: 'ST04',
                        value: '11~12개월',
                        description: [
                            '주변 환경에 대한 호기심이 커져요.',
                            '기본적인 단어를 말하고, 주변의 언어에 반응해요.',
                            '또래 아기와 상호작용하며 간단한 놀이로 사회성을 길러요.',
                            '혼자 서고, 걸음마를 시작하는 시기에요.',
                        ],
                    },
                    {
                        code: 'ST05',
                        value: '13~15개월',
                        description: [
                            '원하는 것을 손으로 가리키며 달라고 해요.',
                            '두세 개의 단어로 짧은 문장을 만들기 시작해요.',
                            '혼자 걷고 계단을 기어 올라가는 등 운동 능력이 향상돼요.',
                            '놀이를 통해 문제 해결 능력과 창의력이 발달하는 시기에요.',
                        ],
                    },
                    {
                        code: 'ST06',
                        value: '16~18개월',
                        description: [
                            '한 손을 잡고 계단을 오르거나 서툴게 뛰기 시작해요.',
                            '어휘가 늘어나고 간단한 문장을 사용해 감정을 표현해요.',
                            '자기 주도적인 행동이 두드러지며 독립적으로 놀이를 해요.',
                            '탐색 욕구가 강해져 주변에 대한 호기심을 가지는 시기에요.',
                        ],
                    },
                    {
                        code: 'ST07',
                        value: '19~24개월',
                        description: [
                            '걷기, 뛰기 등 다양한 이동 능력이 더욱 향상돼요.',
                            '간단한 문장을 만들고 자신의 생각이나 감정을 표현해요.',
                            '다른 아기들과의 상호작용을 통해 사회성을 더욱 길러요.',
                            '다양한 물체를 탐색하며 문제 해결 능력이 발달하는 시기에요.',
                        ],
                    },
                ],
            },
        ],
        // 설정
        config: [
            {
                _id: 'shippingFees',
                title: '배송비',
                value: 3500,
            },
            {
                _id: 'freeShippingFees',
                title: '배송비 무료 금액',
                value: 50000,
            },
        ],
    };
};
